name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Install black & pylint
        run: pip3 install --user black==20.8b1 pylint==2.5.3 astroid==2.4.2
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Configure git credentials
        if: env.run_tests
        run: |
          echo 'https://10xbuild:${{secrets.TENX_DEV_TOKEN}}@github.com' >~/.git-credentials
          chmod 600 ~/.git-credentials
          git config --global credential.helper store
      - name: Check Python black formatting
        run: ~/.local/bin/black --check --diff ./ lib/testing/*py
      # - name: Check for pylint errors
      #   run: >
      #     pylint --rcfile=.pylintrc lib/testing/*py;
      - name: Install cargo/rustc
        run: |
          case $(rustc --version) in
            "rustc 1.53.0"*) ;;
            *) rustup default 1.53.0
               ;;
          esac
          rustup component add rustfmt
          rustc --version
          rustfmt --version
      - name: Check rust formatting
        run: cargo fmt -- --check
      - name: Run cargo check
        run: cargo check --all-targets
      - name: Run cargo build
        run: cargo build
      - name: Install py requirements
        run: pip install pysam
      - name: Run metric test
        run: |
          cd data/
          make metrics ref=GRCh38-2020-A-chrM
      - uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: code-coverage.mdt
      - name: Check if comparison metrics have changed
        run: diff comparison_metrics.txt ../lib/testing/comparison_metrics.txt
